# WhatATheme
markdown: kramdown
# URL of the Site
url: 'https://aistat.org'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: AI Statistic Consulting
# Description of the Site
description: Surajit Ray
# University Name
university: The University of Glasgow
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Medical Imaging, Mixture models, Statistics, Functional Data Analysis
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/consulting.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: surajit.ray@glasgow.ac.uk
twitter_username: surajitstat

linkedin_username: surajit-ray-51ab7021
github_username:  surajitstat


# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Surajit Ray

# Name of the Author
author-name: Surajit Ray
# URL for the Image of the Author
author-image: https://www.gla.ac.uk/media/Media_633760_smxx.jpg
# 60 Words About the Author
author-about: At our AI-Powered Statistical Consulting Solutions, we blend the art and science of statistics with the latest advancements in AI technology to offer you a comprehensive suite of data analysis services. Whether you are in the field of academia, healthcare, finance, marketing, or any industry where data plays a pivotal role, we have the expertise and tools to assist you.

Our services include:

At AIStat, we are incredibly passionate about what we do. We take great pride in offering a wide range of exceptional services that are designed to exceed your expectations. Whether you are in need of innovative web design, flawless content creation, or reliable digital marketing strategies, we have got you covered.

Our talented team of professionals is dedicated to delivering top-notch solutions that not only meet but also surpass your unique requirements. We invest our time and expertise to understand your business goals thoroughly, allowing us to tailor our services perfectly to your needs.

When you choose [Insert Company Name], you can expect nothing less than excellence. We work tirelessly to provide you with exceptional results that will elevate your brand, drive engagement, and maximize your online presence. With our passionate approach and unwavering commitment to your success, we guarantee to deliver the outstanding services you deserve.

Let us be your trusted partner in success. Contact us today to learn more about how we can help you achieve your goals!

Together, we can make your dreams a reality!

    Advanced Data Analysis: We use advanced statistical techniques and machine learning algorithms to find important information in your data, helping you make decisions based on data with confidence.
    Predictive Modeling: Take advantage of AI to create models that can predict trends, identify patterns, and make forecasts to support your business goals.
    Optimization and Automation: Improve your processes and resource allocation with AI-driven solutions that make your operations more efficient, reduce costs, and increase productivity.
    Customized Solutions: We understand that each data challenge is unique. Our team will create solutions tailored to your specific needs, so you can get the most value out of your data.
    Interactive Data Visualization: Turn complex data into actionable insights with interactive dashboards and visuals that are easy for stakeholders to understand and act upon.
    Ethical AI: We always prioritize ethical considerations in all our AI-driven solutions, so your data is handled responsibly and with utmost respect for privacy and security.

Our mission is to empower your organization with the tools and expertise to turn your data into a strategic asset. Collaborate with us, and together we’ll navigate the complexities of data analysis and artificial intelligence to drive innovation, gain a competitive edge, and achieve your goals.

Contact us today to learn how AI-Powered Statistical Consulting Solutions can help you harness the true potential of your data. Make informed decisions that matter with the confidence of data and the power of AI.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://surajitray.org

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-scholar

gems:
  - jekyll/scholar
# Permalink
permalink: "research/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Scholar 
scholar:
  style: chicago-fullnote-bibliography
  sort_by: year
  order: descending
  bibliography_list_tag: ul
