# WhatATheme
markdown: kramdown
# URL of the Site
url: 'https://aistat.org'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: AI Statistic Consulting
# Description of the Site
description: Surajit Ray
# University Name
university: The University of Glasgow
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Medical Imaging, Mixture models, Statistics, Functional Data Analysis
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/consulting.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: surajit.ray@glasgow.ac.uk
twitter_username: surajitstat

linkedin_username: surajit-ray-51ab7021
github_username:  surajitstat


# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Surajit Ray

# Name of the Author
author-name: Surajit Ray
# URL for the Image of the Author
author-image: https://www.gla.ac.uk/media/Media_633760_smxx.jpg
# 60 Words About the Author
author-about: At our AI-Powered Statistical Consulting Solutions, we blend the art and science of statistics with the latest advancements in AI technology to offer you a comprehensive suite of data analysis services. Whether you are in the field of academia, healthcare, finance, marketing, or any industry where data plays a pivotal role, we have the expertise and tools to assist you.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://surajitray.org

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-scholar

gems:
  - jekyll/scholar
# Permalink
permalink: "research/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Scholar 
scholar:
  style: chicago-fullnote-bibliography
  sort_by: year
  order: descending
  bibliography_list_tag: ul
